### ISSUE TITLE
Data loading for FinnGen

### ISSUE THREAD

**Issue by essiviippola** [dsgelab/risteys#129]
Write data harmonization part for FinnGen.

The new data pipeline expects the input data to be in a specific format so that the pipeline can be run on both FinnGen and FinRegistry data.

This data harmonization / pre-processing should result in the following input format:

**Endpoint definitions**

| Column | Description | data type | NA allowed? | Values |
|---|---|---|---|---|
| endpoint | endpoint code name | str | No | – 
| female | Is the endpoint sex-specific (True=female, False=male, NA=unknown) | bool | Yes | True, False, NA |

**Minimum phenotype**

| Column | Description | data type | NA allowed? | Values |
|---|---|---|---|---|
| personid | FinRegistry ID | str | No | – |
| index_person | Is the person a FinRegistry index person | bool | No | True, False |
| birth_year | Birth year as a decimal year | float | no | – |
| death_year | Death year as a decimal year. NA if alive | float | Yes | – |
| female  | Is the person a female (True=female, False=male, NA=unknown) | bool | Yes | True, False, NA |

**First events**

| Column | Description | data type | NA allowed? | Values | Source |
|---|---|---|---|---|---|
| personid | FinRegistry ID | str | No | – |  first events |
| endpoint | endpoint code name | str | No | – | first events |
| age | age at the event | float | No | – | first events |
| year | Year at the event | int | No | – | first events |
| index_person | Is the person a FinRegistry index person | bool | No | True, False, NA | minimum phenotype |
| birth_year | Birth year as a decimal year | float | No | – | minimum phenotype |
| death_year | Death year as a decimal year | float | Yes  | – | minimum phenotype |
| female | Is the person a female (True=female,False=male, NA=unknown) | bool | yes | True, False, NA | minimum phenotype |

**Comment by vincent-octo** [comment]
FinnGen data loading is done (https://github.com/dsgelab/risteys/blob/dev/fg-harmony/pipeline/risteys_pipeline/finngen/load_data.py).

Next step:
- run the new pipeline with this data loading

**Comment by vincent-octo** [comment]
Hey @essiviippola , I have done the loading data part as well as setting up a pipeline script for FinnGen. Currently in its own branch at:
- https://github.com/dsgelab/risteys/blob/dev/fg-harmony/pipeline/risteys_pipeline/finngen/load_data.py
- https://github.com/dsgelab/risteys/blob/dev/fg-harmony/pipeline/scripts/pipeline_finngen.py

Let me know what you think :)

**Comment by vincent-octo** [comment]
Some notes I took that I wanted to share:

- in `cumulative_incidence_function`, it would be easier to handle by returning data always of the same type. For example a DataFrame or an empty DataFrame when nothing was computed, instead of a DataFrame or an empty list as now. This is how I handle its call now and it doesn't feel very clean: https://github.com/dsgelab/risteys/blob/2b0544e5404301a5938c0dcaa180359887ba8f18/pipeline/scripts/pipeline_finngen.py#L70

- I just saw in #173  you planned to move code common to FinnGen and FinRegistry in `/pipeline`, and I had the same thought :)

- I am using `csv.excel_tab` instead of `sep=";"`, seems more robust at least for FinnGen files. https://github.com/dsgelab/risteys/blob/2b0544e5404301a5938c0dcaa180359887ba8f18/pipeline/risteys_pipeline/finngen/load_data.py#L54

- I am using `np.nan` instead of `pd.NA` as the latter seems to have an experimental status https://pandas.pydata.org/pandas-docs/stable/user_guide/missing_data.html#experimental-na-scalar-to-denote-missing-values

**Comment by essiviippola** [comment]
Hi @vincent-octo, good job! 🙌  So cool seeing the pipeline code used here. Thanks for the comments as well! I agree and I'll make the changes soon.

Here are my notes: 

* In FinRegistry, I'm using the [`config.py`](https://github.com/dsgelab/risteys/blob/dev/risteys-pipeline/pipeline/risteys_pipeline/config.py) file for handling file paths instead of command-line arguments. I like the config approach better for traceability. What do you think? 

* I propose we use docstrings for functions. I've found them super helpful! I'm using [Google-style docstrings](https://google.github.io/styleguide/pyguide.html#38-comments-and-docstrings).

**Comment by vincent-octo** [comment]
Hey, good points!

About using `config.py`, I will try to use it! I remember first I tried to use it but somehow decided otherwise, can't remember why though 😅.

Thanks for the reminder about docstrings, I am definitely planning to use it!

**Comment by vincent-octo** [comment]
I now use the config file https://github.com/dsgelab/risteys/pull/161/commits/b1db2329d1b54f07f0c1ddba56dee81c821fb99e .
I prefer not to publish the real data path there so I leave them empty on GitHub.
