### ISSUE TITLE
Add new "Relationships" section to FR-FG Risteys

### ISSUE THREAD

**Issue by SaraKoskelainen** [dsgelab/risteys#188]
Original plan (issue name was "Add Correlations section to FR-FG Risteys and rename"): 
- [ ] Get correlations section back to FR-FG version as it is now in FinnGen Risteys & show clearly that it's FinnGen-only analysis

- [ ] Rename correlations to "Genetic analyses" --> show to Andrea as suggestion

Data files:
- corr_pheno-r8v4_geno-r8v4_full-join__2021-11-23.csv
- dummy__r9_fg_r2_0_8_p_5e_08_keep_cs.variants__small-headers__2022-05-02.csv

---

**Updated plan:** combine "Correlations" and "Survival ananysis" tables of FinnGen Risteys into one "Relationships" table
- [x] Plan and decide results to be shown

> - N & case overlap from both projects

> - "Associations": HR from FR. Comes from survival analysis

> - "Genetic analyses": RG from FG

> - GWS hits and Coloc GWS hits from FG

- [x] Plan, draft, and decide look of the results table in the UI
- [x] Implement the table, including expansion parts for follow-up years, sorting, handling of missing results and omitted endpoints
- [x] Backend changes to handle the data
- [x] Get and import the data
- [x] Documentation: documentation page & help boxes
- [ ] remember to add links to Coloc GWS hits

**Comment by SaraKuitunen** [comment]
Transferring task to @vincent-octo because of offboarding.

TODO:
- [ ] Add coloc hits links, see WIP branch [FR_FG_WIP_coloc_hits_links](https://github.com/dsgelab/risteys/tree/FR_FG_WIP_coloc_hits_links) 
- [ ] Make loading of the Relationships table faster. Table is slow to load, sometimes so slow that at least on localhost can lead to DB connection error. For some endpoints, at least for Z21_OTHER_SPECIAL_EXAM_INVES_PERSONS_WO_COMPLA_REPOR_DIAGNOSIS, loading of the table gets stuck and does not lead properly.
- [ ] Have proper testing

**Comment by vincent-octo** [comment]
**Status:** marking as Complete, as the next steps are now in separate tasks.
