### ISSUE TITLE
Make table for endpoint definition with intermediate case couts

### ISSUE THREAD

**Issue by SaraKuitunen** [dsgelab/risteys#197]
- [x] first version to be used in the beta release: only FG counts (8b667c9)
- [x] final version with R10 counts from FR & FG (ac12155)
- [ ] get counts from FR & import to DB
- [ ] + possible other updates (e.g. help button)

**Comment by vincent-octo** [comment]
**Status:** Blocked
1. Endpointter run is currently being done but without the intermediate case counts (due to space / memory limitations)
2. Intermediate case counts will be done later by Andrius, so waiting for it for now.

Then, will need some dev to update the backend code to import the intermediate case counts for 2 different datasets (for now handles only 1).
