### ISSUE TITLE
Data requiring

### ISSUE THREAD

**Issue by greatdepression32** [dsgelab/risteys#242]
I would like to request basic information regarding the control groups (consisting of a total of 349,539 cases) associated with aortic dissection or aortic aneurysm. Specifically, I am interested in obtaining information about the gender distribution and age demographics of these control groups. Thanks.
![1234](https://github.com/dsgelab/risteys/assets/135518773/803cb2b5-3b82-49a2-ad8a-65adb68eb293)

**Comment by vincent-octo** [comment]
Hello,

Thanks for your question.

I am afraid this information is not directly accessible.

However, since these 2 endpoints have a rather small number of cases you can get a sense of the gender balance of their control groups by looking at a very broad endpoint.
For example, the endpoint ANY_HILMO has 209784 females and 164334 males.

Hope this helps!
