### ISSUE TITLE
What is the meaning of HRs with "*" in "Relationships between endpoints" table for time-to-event analysis ?

### ISSUE THREAD

**Issue by stef-mueller** [dsgelab/risteys#259]
Hi Risteys Team,

First, thank you for contious work on the amazing resource that is Risteys! I am a huge fan :)
In the "Relationships between endpoints" table some hazard ratios of the time-to-event analysis are denoted with "*". I presume this relates to the Pvalue of the analysis. Is that correct, and if so which threshold was used?

Many thanks and best wishes, Stefanie

**Comment by vincent-octo** [comment]
Hello @stef-mueller , thanks for the kind words :)

Your comment made me realize that this `*` is not very intuitive. 😅 
It is actually not related to the p-value, it instead indicates that the precise number of study subjects cannot be displayed in order to safeguard privacy. (This explanation shows up on hovering over the `*`, but easy to miss)

**Comment by stef-mueller** [comment]
Thank you very much for the info Vincent!
