### ISSUE TITLE
Show control definition and the number of controls

### ISSUE THREAD

**Issue by vincent-octo** [dsgelab/risteys#33]

**Comment by anamariaUIC** [comment]
Hi,

Can you please tell me how do I see which controls (or number of controls) were used for a particular phenotype, let's say this one: https://risteys.finngen.fi/phenocode/H7_RETINOPATHYDIAB#summary-statistics

Did you just use cases listed with ICD codes and controls are everyone else in the cohort?

Thanks
Ana

**Comment by vincent-octo** [comment]
Hi @anamariaUIC  and thanks for asking!

In the data that you see in Risteys, the controls are defined as "everyone else that is not a case". More details on the specifics of Risteys data analyses can be found here: https://risteys.finngen.fi/documentation.

However, it needs to be pointed out that some endpoints have custom definition for their controls. Risteys doesn't use or show those for now unfortunately, but this issue is open to track the progress of that.

These control definitions can be seen in the "control definition file" in FinnGen data: file named `finngen_R8_control_definitions.txt` in the phenotype data for DF8, or accessible [online](https://www.finngen.fi/en/researchers/clinical-endpoints)  up to DF7.
To my knowledge these control definitions are used for running the GWAS at https://results.finngen.fi (public version: https://r5.finngen.fi/).

For H7_RETINOPATHYDIAB, the control definition used in GWAS is everyone except cases of H7_RETINOPATHYDIAB and H7_CHOROIDRETINA.

Hope this helps :slightly_smiling_face:  !

**Comment by anamariaUIC** [comment]
Hi Vincent,

Thank you so much for getting back to me. It is news to me that you have R8 version of the data. Can you please share with me link where I can export phenotypes and case/control numbers online for R8?
I only know about this website to do that for R5: https://r5.finngen.fi/

Thanks
Ana


On Sep 9, 2021, at 2:25 AM, vincent ***@***.******@***.***>> wrote:



Hi @anamariaUIC<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FanamariaUIC&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355820391%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=gPkY4pT8sDK9BzkQsrc7fZ4RVLAegnlHwWIXSR6pu%2FQ%3D&reserved=0> and thanks for asking!

In the data that you see in Risteys, the controls are defined as "everyone else that is not a case". More details on the specifics of Risteys data analyses can be found here: https://risteys.finngen.fi/documentation<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fristeys.finngen.fi%2Fdocumentation&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355830373%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=2xlcPVideOrv%2Fl2lcetha8h2Z2SStNuXGsxmWOCdFSo%3D&reserved=0>.

However, it needs to be pointed out that some endpoints have custom definition for their controls. Risteys doesn't use or show those for now unfortunately, but this issue is open to track the progress of that.

These control definitions can be seen in the "control definition file" in FinnGen data: file named finngen_R8_control_definitions.txt in the phenotype data for DF8, or accessible online<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.finngen.fi%2Fen%2Fresearchers%2Fclinical-endpoints&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355830373%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=1to7FOdPrUCUXocpol7qfK1bLl523MbWJ9X51Re%2B0Ws%3D&reserved=0> up to DF7.
To my knowledge these control definitions are used for running the GWAS at https://results.finngen.fi<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fresults.finngen.fi%2F&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355840372%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ffEptzHl34QOvfNGkGtkOPQAgqNQANKA3i0DIeSq1DE%3D&reserved=0> (public version: https://r5.finngen.fi/<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fr5.finngen.fi%2F&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355840372%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=x2qJrCseEWGuK9S1v1SsceJAPZ0BeldSwzdYyQOEr1Y%3D&reserved=0>).

For H7_RETINOPATHYDIAB, the control definition used in GWAS is everyone except cases of H7_RETINOPATHYDIAB and H7_CHOROIDRETINA.

Hope this helps 🙂 !

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsgelab%2Fristeys%2Fissues%2F33%23issuecomment-915833216&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355850367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4r%2FazCPJREuDPKGN%2FIFsib4rd56qDQZs1bZE%2BkrpBng%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUHBH5CDABYYJVZMTANGL2DUBBOO3ANCNFSM4JNPVNVQ&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355850367%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=lshHzhR5vFDnQS7XekLAamxTQJ3Htuu%2FSWz5iRxlaf8%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355860362%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=V9jNkzeIZXBCxciVrk27K%2FZM1nutYJxc63kTf7bRXto%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Canamaria%40uic.edu%7Cff96bf5b86174ae96fc508d9736302dc%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667691355860362%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=Z8HWue5fSDSa%2B%2F8Ox8pWFEuue6k0Y%2BPkSfkg%2BU4yA9Q%3D&reserved=0>.

**Comment by vincent-octo** [comment]
Hi Ana,

Most FinnGen results are subject to an embargo period of 1 year (more info on [accessing the results](https://www.finngen.fi/en/access_results) and the [FinnGen data freezes and releases](https://finngen.gitbook.io/finngen-analyst-handbook/finngen-data-specifics/finngen-data-freezes-and-releases)). That means that you can access the latest release (DF8) only if you are part of FinnGen.

If you are part of FinnGen, then the DF8 release is accessible using the FinnGen sandbox (see the [Working in the Sandbox](https://finngen.gitbook.io/finngen-analyst-handbook/working-in-the-sandbox/how-to-get-started-with-sandbox) documentation).

However, if you are not part of FinnGen you still have open access to:
- [Risteys](https://risteys.finngen.fi/) with latest release (currently crunching the DF8 data, so for now it is still the DF7).
- [PheWeb](https://r5.finngen.fi/) with the currently public release (DF5 as of writing)

– Vincent

**Comment by anamariaUIC** [comment]
Hi Vincent,

Thank you so much for this explanation. I requested the access to the summary statistics  (by filling this online form https://www.finngen.fi/en/access_results) but I didn’t get R7 version from your support, I received access to R5. (link to it)

Can you please tell me how I can request the newest available R7 version?

Thanks
Ana

On Sep 9, 2021, at 8:52 AM, vincent ***@***.******@***.***>> wrote:



Hi Ana,

Most FinnGen results are subject to an embargo period of 1 year (more info on accessing the results<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fwww.finngen.fi%2Fen%2Faccess_results&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674794058%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=o9ogCJN2Uk1Psu8HLGxbt6MDSE7cYT7aqPBnHkIv2A0%3D&reserved=0> and the FinnGen data freezes and releases<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffinngen.gitbook.io%2Ffinngen-analyst-handbook%2Ffinngen-data-specifics%2Ffinngen-data-freezes-and-releases&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674804055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kzMc11KtXIiAzYpNTt648GLSMYQUziUdGxl2%2BkYvhbA%3D&reserved=0>). That means that you can access the latest release (DF8) only if you are part of FinnGen.

If you are part of FinnGen, then the DF8 release is accessible using the FinnGen sandbox (see the Working in the Sandbox<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Ffinngen.gitbook.io%2Ffinngen-analyst-handbook%2Fworking-in-the-sandbox%2Fhow-to-get-started-with-sandbox&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674804055%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=ZUyMyZt1LNxnnfBaw73VewNK4NFtwJD0pqOHtK69GgU%3D&reserved=0> documentation).

However, if you are not part of FinnGen you still have open access to:

  *   Risteys<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fristeys.finngen.fi%2F&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674814048%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=4TiAZLeKkHwut1XGnV2E3cCM7CwRdew8hfNlEuu%2FZe4%3D&reserved=0> with latest release (currently crunching the DF8 data, so for now it is still the DF7).
  *   PheWeb<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fr5.finngen.fi%2F&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674814048%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sV0vsJWZ%2B85PNn4c7g3DWbek1oECBbFAFHfBzFPKKCM%3D&reserved=0> with the currently public release (DF5 as of writing)

– Vincent

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsgelab%2Fristeys%2Fissues%2F33%23issuecomment-916118255&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674824041%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=XbiXDxa9hPagQ99SCwLVZC8DOcUlH%2F5xn%2Bqdl9QwOeg%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUHBH5DWDNTVEL5XBCBSPDLUBC32ZANCNFSM4JNPVNVQ&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674824041%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=zswg0nvsvJL%2Fyo4KrEpaQJN45CBcvQRrlWK0lCTUGxE%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674834038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=YGGwB57WNvAeNRn3DNOdDcB0VndbYVY2%2FcqR7zj0Zd4%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Canamaria%40uic.edu%7C071e3e16e91c406a4b5608d9739919c8%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667923674834038%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sttsASJFE8ud5eBwt9BkIcz3oUxzR4Q9%2FYJjIoKxL5M%3D&reserved=0>.

**Comment by vincent-octo** [comment]
Hi Ana,

I think that by filling this form you should now have a @finngen.fi account.
If that is correct, you should have access to the latest (R7 as of writing) GWAS summary statistics here: https://results.finngen.fi

– Vincent

**Comment by anamariaUIC** [comment]
Hi Vincent,

I tried the link you supplied, using my email: ***@***.******@***.***> which I used to create my account on FinnGen but this is what I get (in attach). Can you please advise?

Thanks
Ana
***@***.***

On Sep 9, 2021, at 9:22 AM, vincent ***@***.******@***.***>> wrote:



Hi Ana,

I think that by filling this form you should now have a @FINNGEN<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FFINNGEN&data=04%7C01%7Canamaria%40uic.edu%7C0105b2073ec24fa1721d08d9739d52f9%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667941808789702%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=sQlIqgwuUwwiux7IrUXEcxQrFpgwauyo2QGeStCXWRA%3D&reserved=0>.fi account.
If that is correct, you should have access to the latest (R7 as of writing) GWAS summary statistics here: https://results.finngen.fi<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fresults.finngen.fi%2F&data=04%7C01%7Canamaria%40uic.edu%7C0105b2073ec24fa1721d08d9739d52f9%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667941808799697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=CvBwXuoVx39JiW6j2aog8mEbO9OHI%2FfOtn5O4Nwg%2BJc%3D&reserved=0>

– Vincent

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdsgelab%2Fristeys%2Fissues%2F33%23issuecomment-916145668&data=04%7C01%7Canamaria%40uic.edu%7C0105b2073ec24fa1721d08d9739d52f9%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667941808799697%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=RgDQlb0XllVCUD%2BxedaTVAnrWRZjhJN5sbKp%2Fexuuo8%3D&reserved=0>, or unsubscribe<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FAUHBH5CQIBXIAWM7XTAM7HTUBC7MFANCNFSM4JNPVNVQ&data=04%7C01%7Canamaria%40uic.edu%7C0105b2073ec24fa1721d08d9739d52f9%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667941808809694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=BeDxtGZw%2B4%2BDD4VcXSBUk4Ue0dWt3ArO6mhSusBjtyg%3D&reserved=0>.
Triage notifications on the go with GitHub Mobile for iOS<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapps.apple.com%2Fapp%2Fapple-store%2Fid1477376905%3Fct%3Dnotification-email%26mt%3D8%26pt%3D524675&data=04%7C01%7Canamaria%40uic.edu%7C0105b2073ec24fa1721d08d9739d52f9%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667941808809694%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=pl%2F9icnDZ9XHfejIJDdkA33TP%2BUf1VlYKjLGjhyjOmc%3D&reserved=0> or Android<https://nam04.safelinks.protection.outlook.com/?url=https%3A%2F%2Fplay.google.com%2Fstore%2Fapps%2Fdetails%3Fid%3Dcom.github.android%26referrer%3Dutm_campaign%253Dnotification-email%2526utm_medium%253Demail%2526utm_source%253Dgithub&data=04%7C01%7Canamaria%40uic.edu%7C0105b2073ec24fa1721d08d9739d52f9%7Ce202cd477a564baa99e3e3b71a7c77dd%7C0%7C0%7C637667941808819685%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C1000&sdata=kytd2fTnTxiYNRaqKkQCNMrEszIZYhICWHm%2FM0DcSfo%3D&reserved=0>.

**Comment by vincent-octo** [comment]
Hi Ana,

It seems GitHub has redacted your email address and removed your attachment, so I cannot see them.

Would you mind contacting me through https://airtable.com/shrTzTwby7JhFEqi6 so that I have your email address? Then we can continue our discussion via email more easily.

–Vincent
