### ISSUE TITLE
smartphone compatibility

### ISSUE THREAD

**Issue by andgan** [dsgelab/risteys#51]
improve smartphone compatibility. currently several features do not display correctly.

**Comment by vincent-octo** [comment]
I thought of that before (see #11 ) but I abandoned the idea since:
- few people use Risteys on a mobile phone
- requires lots of work to make it work properly (especially for tables and plots, which are most of the elements of Risteys)

But maybe we can improve at least some parts for mobile?
@andgan what are the "several features that do not display correctly"?

**Comment by andgan** [comment]
Tables and plot don’t display properly. True that few people uses now on mobile. But if we are going to sponsor it, e.g. via twitter, most people will initially access to it via smartphone and we don’t want to give the impression that the portal is “buggy”
